// generated by volcano.

package android.support.loader;

public final class R {

    public static final class attr {
        public static final int alpha = _RM.attr.alpha;
        public static final int font = _RM.attr.font;
        public static final int fontProviderAuthority = _RM.attr.fontProviderAuthority;
        public static final int fontProviderCerts = _RM.attr.fontProviderCerts;
        public static final int fontProviderFetchStrategy = _RM.attr.fontProviderFetchStrategy;
        public static final int fontProviderFetchTimeout = _RM.attr.fontProviderFetchTimeout;
        public static final int fontProviderPackage = _RM.attr.fontProviderPackage;
        public static final int fontProviderQuery = _RM.attr.fontProviderQuery;
        public static final int fontStyle = _RM.attr.fontStyle;
        public static final int fontVariationSettings = _RM.attr.fontVariationSettings;
        public static final int fontWeight = _RM.attr.fontWeight;
        public static final int ttcIndex = _RM.attr.ttcIndex;
    }

    public static final class color {
        public static final int notification_action_color_filter = _RM.color.notification_action_color_filter;
        public static final int notification_icon_bg_color = _RM.color.notification_icon_bg_color;
        public static final int ripple_material_light = _RM.color.ripple_material_light;
        public static final int secondary_text_default_material_light = _RM.color.secondary_text_default_material_light;
    }

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = _RM.dimen.compat_button_inset_horizontal_material;
        public static final int compat_button_inset_vertical_material = _RM.dimen.compat_button_inset_vertical_material;
        public static final int compat_button_padding_horizontal_material = _RM.dimen.compat_button_padding_horizontal_material;
        public static final int compat_button_padding_vertical_material = _RM.dimen.compat_button_padding_vertical_material;
        public static final int compat_control_corner_material = _RM.dimen.compat_control_corner_material;
        public static final int compat_notification_large_icon_max_height = _RM.dimen.compat_notification_large_icon_max_height;
        public static final int compat_notification_large_icon_max_width = _RM.dimen.compat_notification_large_icon_max_width;
        public static final int notification_action_icon_size = _RM.dimen.notification_action_icon_size;
        public static final int notification_action_text_size = _RM.dimen.notification_action_text_size;
        public static final int notification_big_circle_margin = _RM.dimen.notification_big_circle_margin;
        public static final int notification_content_margin_start = _RM.dimen.notification_content_margin_start;
        public static final int notification_large_icon_height = _RM.dimen.notification_large_icon_height;
        public static final int notification_large_icon_width = _RM.dimen.notification_large_icon_width;
        public static final int notification_main_column_padding_top = _RM.dimen.notification_main_column_padding_top;
        public static final int notification_media_narrow_margin = _RM.dimen.notification_media_narrow_margin;
        public static final int notification_right_icon_size = _RM.dimen.notification_right_icon_size;
        public static final int notification_right_side_padding_top = _RM.dimen.notification_right_side_padding_top;
        public static final int notification_small_icon_background_padding = _RM.dimen.notification_small_icon_background_padding;
        public static final int notification_small_icon_size_as_large = _RM.dimen.notification_small_icon_size_as_large;
        public static final int notification_subtext_size = _RM.dimen.notification_subtext_size;
        public static final int notification_top_pad = _RM.dimen.notification_top_pad;
        public static final int notification_top_pad_large_text = _RM.dimen.notification_top_pad_large_text;
    }

    public static final class drawable {
        public static final int notification_action_background = _RM.drawable.notification_action_background;
        public static final int notification_bg = _RM.drawable.notification_bg;
        public static final int notification_bg_low = _RM.drawable.notification_bg_low;
        public static final int notification_bg_low_normal = _RM.drawable.notification_bg_low_normal;
        public static final int notification_bg_low_pressed = _RM.drawable.notification_bg_low_pressed;
        public static final int notification_bg_normal = _RM.drawable.notification_bg_normal;
        public static final int notification_bg_normal_pressed = _RM.drawable.notification_bg_normal_pressed;
        public static final int notification_icon_background = _RM.drawable.notification_icon_background;
        public static final int notification_template_icon_bg = _RM.drawable.notification_template_icon_bg;
        public static final int notification_template_icon_low_bg = _RM.drawable.notification_template_icon_low_bg;
        public static final int notification_tile_bg = _RM.drawable.notification_tile_bg;
        public static final int notify_panel_notification_icon_bg = _RM.drawable.notify_panel_notification_icon_bg;
    }

    public static final class id {
        public static final int action_container = _RM.id.action_container;
        public static final int action_divider = _RM.id.action_divider;
        public static final int action_image = _RM.id.action_image;
        public static final int action_text = _RM.id.action_text;
        public static final int actions = _RM.id.actions;
        public static final int async = _RM.id.async;
        public static final int blocking = _RM.id.blocking;
        public static final int chronometer = _RM.id.chronometer;
        public static final int forever = _RM.id.forever;
        public static final int icon = _RM.id.icon;
        public static final int icon_group = _RM.id.icon_group;
        public static final int info = _RM.id.info;
        public static final int italic = _RM.id.italic;
        public static final int line1 = _RM.id.line1;
        public static final int line3 = _RM.id.line3;
        public static final int normal = _RM.id.normal;
        public static final int notification_background = _RM.id.notification_background;
        public static final int notification_main_column = _RM.id.notification_main_column;
        public static final int notification_main_column_container = _RM.id.notification_main_column_container;
        public static final int right_icon = _RM.id.right_icon;
        public static final int right_side = _RM.id.right_side;
        public static final int tag_transition_group = _RM.id.tag_transition_group;
        public static final int tag_unhandled_key_event_manager = _RM.id.tag_unhandled_key_event_manager;
        public static final int tag_unhandled_key_listeners = _RM.id.tag_unhandled_key_listeners;
        public static final int text = _RM.id.text;
        public static final int text2 = _RM.id.text2;
        public static final int time = _RM.id.time;
        public static final int title = _RM.id.title;
    }

    public static final class integer {
        public static final int status_bar_notification_info_maxnum = _RM.integer.status_bar_notification_info_maxnum;
    }

    public static final class layout {
        public static final int notification_action = _RM.layout.notification_action;
        public static final int notification_action_tombstone = _RM.layout.notification_action_tombstone;
        public static final int notification_template_custom_big = _RM.layout.notification_template_custom_big;
        public static final int notification_template_icon_group = _RM.layout.notification_template_icon_group;
        public static final int notification_template_part_chronometer = _RM.layout.notification_template_part_chronometer;
        public static final int notification_template_part_time = _RM.layout.notification_template_part_time;
    }

    public static final class string {
        public static final int status_bar_notification_info_overflow = _RM.string.status_bar_notification_info_overflow;
    }

    public static final class style {
        public static final int TextAppearance_Compat_Notification = _RM.style.TextAppearance_Compat_Notification;
        public static final int TextAppearance_Compat_Notification_Info = _RM.style.TextAppearance_Compat_Notification_Info;
        public static final int TextAppearance_Compat_Notification_Line2 = _RM.style.TextAppearance_Compat_Notification_Line2;
        public static final int TextAppearance_Compat_Notification_Time = _RM.style.TextAppearance_Compat_Notification_Time;
        public static final int TextAppearance_Compat_Notification_Title = _RM.style.TextAppearance_Compat_Notification_Title;
        public static final int Widget_Compat_NotificationActionContainer = _RM.style.Widget_Compat_NotificationActionContainer;
        public static final int Widget_Compat_NotificationActionText = _RM.style.Widget_Compat_NotificationActionText;
    }

    public static final class styleable {
        public static final int[] ColorStateListItem = _RM.styleable.ColorStateListItem;
        public static final int ColorStateListItem_alpha = _RM.styleable.ColorStateListItem_alpha;
        public static final int ColorStateListItem_android_alpha = _RM.styleable.ColorStateListItem_android_alpha;
        public static final int ColorStateListItem_android_color = _RM.styleable.ColorStateListItem_android_color;
        public static final int[] FontFamily = _RM.styleable.FontFamily;
        public static final int FontFamily_fontProviderAuthority = _RM.styleable.FontFamily_fontProviderAuthority;
        public static final int FontFamily_fontProviderCerts = _RM.styleable.FontFamily_fontProviderCerts;
        public static final int FontFamily_fontProviderFetchStrategy = _RM.styleable.FontFamily_fontProviderFetchStrategy;
        public static final int FontFamily_fontProviderFetchTimeout = _RM.styleable.FontFamily_fontProviderFetchTimeout;
        public static final int FontFamily_fontProviderPackage = _RM.styleable.FontFamily_fontProviderPackage;
        public static final int FontFamily_fontProviderQuery = _RM.styleable.FontFamily_fontProviderQuery;
        public static final int[] FontFamilyFont = _RM.styleable.FontFamilyFont;
        public static final int FontFamilyFont_android_font = _RM.styleable.FontFamilyFont_android_font;
        public static final int FontFamilyFont_android_fontStyle = _RM.styleable.FontFamilyFont_android_fontStyle;
        public static final int FontFamilyFont_android_fontVariationSettings = _RM.styleable.FontFamilyFont_android_fontVariationSettings;
        public static final int FontFamilyFont_android_fontWeight = _RM.styleable.FontFamilyFont_android_fontWeight;
        public static final int FontFamilyFont_android_ttcIndex = _RM.styleable.FontFamilyFont_android_ttcIndex;
        public static final int FontFamilyFont_font = _RM.styleable.FontFamilyFont_font;
        public static final int FontFamilyFont_fontStyle = _RM.styleable.FontFamilyFont_fontStyle;
        public static final int FontFamilyFont_fontVariationSettings = _RM.styleable.FontFamilyFont_fontVariationSettings;
        public static final int FontFamilyFont_fontWeight = _RM.styleable.FontFamilyFont_fontWeight;
        public static final int FontFamilyFont_ttcIndex = _RM.styleable.FontFamilyFont_ttcIndex;
        public static final int[] GradientColor = _RM.styleable.GradientColor;
        public static final int GradientColor_android_centerColor = _RM.styleable.GradientColor_android_centerColor;
        public static final int GradientColor_android_centerX = _RM.styleable.GradientColor_android_centerX;
        public static final int GradientColor_android_centerY = _RM.styleable.GradientColor_android_centerY;
        public static final int GradientColor_android_endColor = _RM.styleable.GradientColor_android_endColor;
        public static final int GradientColor_android_endX = _RM.styleable.GradientColor_android_endX;
        public static final int GradientColor_android_endY = _RM.styleable.GradientColor_android_endY;
        public static final int GradientColor_android_gradientRadius = _RM.styleable.GradientColor_android_gradientRadius;
        public static final int GradientColor_android_startColor = _RM.styleable.GradientColor_android_startColor;
        public static final int GradientColor_android_startX = _RM.styleable.GradientColor_android_startX;
        public static final int GradientColor_android_startY = _RM.styleable.GradientColor_android_startY;
        public static final int GradientColor_android_tileMode = _RM.styleable.GradientColor_android_tileMode;
        public static final int GradientColor_android_type = _RM.styleable.GradientColor_android_type;
        public static final int[] GradientColorItem = _RM.styleable.GradientColorItem;
        public static final int GradientColorItem_android_color = _RM.styleable.GradientColorItem_android_color;
        public static final int GradientColorItem_android_offset = _RM.styleable.GradientColorItem_android_offset;
    }

    private static final class _RM extends com.qqq.WXhongbao.R { }
}
